import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextUiProvider } from "./Providers/NextUiProvider";
import MainBar from "./Components/MainNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} background-main-color`}>
        <NextUiProvider>
          <MainBar />
          

          {children}
        </NextUiProvider>
      </body>
    </html>
  );
}
